# here are some words

In [31]:
import pandas as pd
#from pandas import ExcelWriter
#from pandas import ExcelFile
pemData = pd.read_csv("/Users/heidilooker/Desktop/Data Project/Rare Book and Manuscript Library/FY1819/RBML 011819/P2_00439.126.csv", header = None, names=["Date and Time","Temp","%RH"],skiprows = 4)
pemData





#print(pemData)
#print ("Column headings:")
#exportData = pd.DataFrame(pemData)
#exportData = exportData[['DATE AND TIME', 'TEMP', '%RH', 'YYYY-MM-DD']]

       Date and Time  Temp  %RH
0     12/17/18 12:30  58.8   48
1     12/17/18 13:00  58.8   48
2     12/17/18 13:30  58.8   48
3     12/17/18 14:00  58.8   48
4     12/17/18 14:30  58.8   48
5     12/17/18 15:00  58.8   48
6     12/17/18 15:30  58.8   48
7     12/17/18 16:00  58.8   48
8     12/17/18 16:30  58.8   48
9     12/17/18 17:00  58.8   48
10    12/17/18 17:30  58.8   48
11    12/17/18 18:00  58.8   48
12    12/17/18 18:30  58.8   48
13    12/17/18 19:00  58.8   48
14    12/17/18 19:30  58.8   48
15    12/17/18 20:00  58.8   48
16    12/17/18 20:30  59.0   47
17    12/17/18 21:00  58.8   46
18    12/17/18 21:30  58.8   45
19    12/17/18 22:00  58.8   45
20    12/17/18 22:30  58.6   44
21    12/17/18 23:00  58.6   44
22    12/17/18 23:30  58.8   44
23     12/18/18 0:00  58.8   45
24     12/18/18 0:30  58.8   46
25     12/18/18 1:00  58.8   47
26     12/18/18 1:30  58.8   47
27     12/18/18 2:00  58.8   48
28     12/18/18 2:30  58.8   48
29     12/18/18 3:00  58.8   48
...              ...   ...  ...
1517    1/18/19 3:00  59.1   48
1518    1/18/19 3:30  59.1   48
1519    1/18/19 4:00  59.1   48
1520    1/18/19 4:30  59.1   48
1521    1/18/19 5:00  59.1   48
1522    1/18/19 5:30  59.1   48
1523    1/18/19 6:00  59.1   48
1524    1/18/19 6:30  59.1   48
1525    1/18/19 7:00  59.1   48
1526    1/18/19 7:30  59.1   48
1527    1/18/19 8:00  59.1   48
1528    1/18/19 8:30  59.1   48
1529    1/18/19 9:00  59.1   48
1530    1/18/19 9:30  59.1   48
1531   1/18/19 10:00  59.1   48
1532   1/18/19 10:30  59.1   48
1533   1/18/19 11:00  59.1   48
1534   1/18/19 11:30  59.1   48
1535   1/18/19 12:00  59.1   48
1536   1/18/19 12:30  59.1   48
1537   1/18/19 13:00  59.3   48
1538   1/18/19 13:30  59.3   48
1539   1/18/19 14:00  59.3   48
1540   1/18/19 14:30  59.3   48
1541   1/18/19 15:00  59.3   48
1542   1/18/19 15:30  59.3   48
1543   1/18/19 16:00  59.3   48
1544   1/18/19 16:30  59.3   48
1545   1/18/19 17:00  59.3   48
1546   1/18/19 17:30  59.3   48

[1547 rows x 3 columns]

In [32]:
pemData.to_csv("/Users/heidilooker/Google Drive (hlooker93@gmail.com)/📚 Grad School Notes/data mashups/A place to store data/new.csv", index=False)